name: gotaxi
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.0.2
  freezed: ^2.3.2
  flutter_bloc: ^8.1.2
  pinput: ^2.2.31
  firebase_auth: ^4.2.10
  firebase_core: ^2.7.1
  equatable: ^2.0.5
  formz: ^0.4.0
  shared_preferences: ^2.0.18
  lottie: ^2.3.0
  fluttertoast: ^8.2.1
  firebase_storage: ^11.0.16
  cloud_firestore: ^4.4.5
  freezed_annotation: ^2.2.0
  logger: ^1.3.0
  image_picker: ^0.8.7
  file_picker: ^5.2.6
  cached_network_image: ^3.2.2
  shimmer: ^2.0.0
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  google_maps_flutter: ^2.2.5
  const_date_time: ^1.0.2
  bloc_concurrency: ^0.2.1
  intl: ^0.17.0
  pretty_dio_logger: ^1.3.1
  auto_route: ^6.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  build_runner: ^2.3.3
  auto_route_generator: ^6.0.3

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/lottie/
    - assets/images/
    - assets/images/users/
    - assets/svg/
    - assets/svg/card/
    - assets/translations/


  fonts:
    - family: SFUIDisplay
      fonts:
        - asset: assets/fonts/SFProDisplay-Light.ttf
          weight: 300
        - asset: assets/fonts/SFProDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/SFProDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/SFProDisplay-Semibold.ttf
          weight: 600
        - asset: assets/fonts/SFProDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/SFProDisplay-Black.ttf
          weight: 900

